const ROLES = {
  ADMIN: "ADMIN",
  COORDINATOR: "COORDINATOR",
  STUDENT: "STUDENT",
  EVALUATOR: "EVALUATOR"
};

const USER_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  BLOCKED: "BLOCKED"
};

const COMPETITION_STATUS = {
  DRAFT: "DRAFT",
  UPCOMING: "UPCOMING",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  ARCHIVED: "ARCHIVED"
};

const TASK_TYPES = {
  CLEANUP: "CLEANUP",
  AWARENESS: "AWARENESS",
  POSTER: "POSTER",
  STREET_PLAY: "STREET_PLAY",
  WASTE_RECOVERY: "WASTE_RECOVERY",
  COMMUNITY_INTERACTION: "COMMUNITY_INTERACTION",
  WASTE_AUDIT: "WASTE_AUDIT",
  OTHER: "OTHER"
};

const TASK_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED"
};

const EVIDENCE_TYPES = {
  PHOTO: "PHOTO",
  VIDEO: "VIDEO",
  DOCUMENT: "DOCUMENT",
  TEXT: "TEXT",
  NUMBER: "NUMBER"
};

const SUBMISSION_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  EVALUATED: "EVALUATED",
  REJECTED: "REJECTED",
  FLAGGED: "FLAGGED"
};

const EVALUATION_DECISION = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  FLAGGED: "FLAGGED"
};

const CALIBRATION_STATUS = {
  CALIBRATION_PASS: "CALIBRATION_PASS",
  CALIBRATION_REVIEW: "CALIBRATION_REVIEW"
};

const NOTIFICATION_TYPES = {
  TASK_REMINDER: "TASK_REMINDER",
  SUBMISSION_REMINDER: "SUBMISSION_REMINDER",
  EVALUATION_ASSIGNED: "EVALUATION_ASSIGNED",
  EVALUATION_RESULT: "EVALUATION_RESULT",
  TEAM_NUDGE: "TEAM_NUDGE",
  SYSTEM: "SYSTEM"
};

const COMMUNITY_VISIBILITY = {
  PRIVATE: "PRIVATE",
  COLLEGE: "COLLEGE",
  PUBLIC: "PUBLIC"
};

const AI_REVIEW_STATUS = {
  PENDING_REVIEW: "PENDING_REVIEW",
  ACCEPTED: "ACCEPTED",
  MODIFIED: "MODIFIED",
  REJECTED: "REJECTED"
};

module.exports = {
  ROLES,
  USER_STATUS,
  COMPETITION_STATUS,
  TASK_TYPES,
  TASK_STATUS,
  EVIDENCE_TYPES,
  SUBMISSION_STATUS,
  EVALUATION_DECISION,
  CALIBRATION_STATUS,
  NOTIFICATION_TYPES,
  COMMUNITY_VISIBILITY,
  AI_REVIEW_STATUS
};

